# Generated by Django 5.0 on 2023-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
