# Generated by Django 5.0 on 2023-12-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_tweet_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
